### ISSUE TITLE
[Dash CLI] Github Login 

### ISSUE THREAD

**Issue by samyakkkk** [Welltested-AI/commanddash#5]
Users can use Dash CLI to author, publish and manage their agents. 

To publish or manage their agents, they need to be logged in. We use "Github Login" as the authentication mechanism. 

Process:
1. User run the command "dash_cli login". 
2. This triggers a request to our backend to get the OauthURL to redirect the user. `{baseURl}/account/github/authenticate`;
3. After user is redirected, and successfully completes that auth, they will be redirected to the url: `"vscode://welltestedai.dash-ai/login-success?access_token={access_token}&refresh_token={refresh_token}"` which should open the terminal back. Now this url was for vscode ext, please check how should it be for the CLI. 
4. The received accessToken is stored locally. 

The access token will be used in future when user tries to publish or manage their agents. If the accessToken expires, users should request for a refresh token on `{baseURl}/account/github/token-refresh`

**Comment by yahu1031** [comment]
Assign this to me, I will take this up.

**Comment by samyakkkk** [comment]
@yahu1031 the CLI will be communicating to the following base URL: [shared privately on slack]. 

It has following endpoint: GET **/account/github/url** which returns the URL to redirect user to for signing in. 

After signed in, the user is redirected to `http://localhost:8080?access_token={access_token}&refresh_token={refresh_token}&email_found={email_found}"` which the server can listen to. 

We also need to handle a case when `email_found` is false (it happens when we do not get an appropriate email back from Github), we need to manually ask user for their email from the CLI and submit it to backend via api: `/account/github/update/email?access_token=${access_token}&email={email}`.

thanks.

**Comment by yahu1031** [comment]
This was closed with reference #10 Please close this issue @samyakkkk

**Comment by samyakkkk** [comment]
Thanks @yahu1031 for the great work on this. Marking done!
